# Generated by sgb2ns, created by Polly Huang
# GRAPH (#nodes #edges id uu vv ww xx yy zz):
# 200 672 transtub(0,4,0,0,{1,126,3,1.000,0.000,0.000},{8,64,3,0.800,0.000,0.000},{6,43,3,0.500,0.000,0.000}) 126 2 3 0 

proc create-topology {nsns node linkBW} {
	upvar $node n
	upvar $nsns ns

	set verbose 1

	if {$verbose} { 
		puts "creating nodes..." 
}
		for {set i 0} {$i < 200} {incr i} {
			set n($i) [$ns node]
	}

	# EDGES (from-node to-node length a b):
	if {$verbose} { 
		puts -nonewline "Creating links 0..."
		flush stdout 
	}
	$ns duplex-link $n(0) $n(13) $linkBW 330ms DropTail
	$ns duplex-link $n(0) $n(10) $linkBW 130ms DropTail
	$ns duplex-link $n(0) $n(1) $linkBW 210ms DropTail
	$ns duplex-link $n(0) $n(2) $linkBW 230ms DropTail
	$ns duplex-link $n(0) $n(4) $linkBW 110ms DropTail
	$ns duplex-link $n(0) $n(5) $linkBW 530ms DropTail
	$ns duplex-link $n(0) $n(7) $linkBW 460ms DropTail
	$ns duplex-link $n(1) $n(29) $linkBW 90ms DropTail
	$ns duplex-link $n(1) $n(27) $linkBW 320ms DropTail
	$ns duplex-link $n(1) $n(20) $linkBW 210ms DropTail
	if {$verbose} { puts -nonewline "10..."; flush stdout }
	$ns duplex-link $n(1) $n(2) $linkBW 150ms DropTail
	$ns duplex-link $n(1) $n(3) $linkBW 340ms DropTail
	$ns duplex-link $n(1) $n(5) $linkBW 350ms DropTail
	$ns duplex-link $n(1) $n(6) $linkBW 250ms DropTail
	$ns duplex-link $n(1) $n(7) $linkBW 260ms DropTail
	$ns duplex-link $n(2) $n(55) $linkBW 80ms DropTail
	$ns duplex-link $n(2) $n(50) $linkBW 160ms DropTail
	$ns duplex-link $n(2) $n(43) $linkBW 240ms DropTail
	$ns duplex-link $n(2) $n(3) $linkBW 330ms DropTail
	$ns duplex-link $n(2) $n(4) $linkBW 190ms DropTail
	if {$verbose} { puts -nonewline "20..."; flush stdout }
	$ns duplex-link $n(2) $n(6) $linkBW 230ms DropTail
	$ns duplex-link $n(3) $n(84) $linkBW 270ms DropTail
	$ns duplex-link $n(3) $n(75) $linkBW 350ms DropTail
	$ns duplex-link $n(3) $n(68) $linkBW 210ms DropTail
	$ns duplex-link $n(3) $n(61) $linkBW 410ms DropTail
	$ns duplex-link $n(3) $n(59) $linkBW 360ms DropTail
	$ns duplex-link $n(3) $n(4) $linkBW 520ms DropTail
	$ns duplex-link $n(3) $n(5) $linkBW 90ms DropTail
	$ns duplex-link $n(3) $n(6) $linkBW 550ms DropTail
	$ns duplex-link $n(3) $n(7) $linkBW 90ms DropTail
	if {$verbose} { puts -nonewline "30..."; flush stdout }
	$ns duplex-link $n(4) $n(132) $linkBW 220ms DropTail
	$ns duplex-link $n(4) $n(125) $linkBW 430ms DropTail
	$ns duplex-link $n(4) $n(121) $linkBW 420ms DropTail
	$ns duplex-link $n(4) $n(117) $linkBW 130ms DropTail
	$ns duplex-link $n(4) $n(115) $linkBW 20ms DropTail
	$ns duplex-link $n(4) $n(106) $linkBW 150ms DropTail
	$ns duplex-link $n(4) $n(98) $linkBW 160ms DropTail
	$ns duplex-link $n(4) $n(91) $linkBW 300ms DropTail
	$ns duplex-link $n(4) $n(5) $linkBW 500ms DropTail
	$ns duplex-link $n(4) $n(7) $linkBW 470ms DropTail
	if {$verbose} { puts -nonewline "40..."; flush stdout }
	$ns duplex-link $n(5) $n(143) $linkBW 270ms DropTail
	$ns duplex-link $n(5) $n(138) $linkBW 80ms DropTail
	$ns duplex-link $n(5) $n(6) $linkBW 540ms DropTail
	$ns duplex-link $n(5) $n(7) $linkBW 150ms DropTail
	$ns duplex-link $n(6) $n(171) $linkBW 210ms DropTail
	$ns duplex-link $n(6) $n(167) $linkBW 330ms DropTail
	$ns duplex-link $n(6) $n(163) $linkBW 230ms DropTail
	$ns duplex-link $n(6) $n(159) $linkBW 310ms DropTail
	$ns duplex-link $n(6) $n(153) $linkBW 400ms DropTail
	$ns duplex-link $n(6) $n(7) $linkBW 490ms DropTail
	if {$verbose} { puts -nonewline "50..."; flush stdout }
	$ns duplex-link $n(7) $n(196) $linkBW 300ms DropTail
	$ns duplex-link $n(7) $n(194) $linkBW 290ms DropTail
	$ns duplex-link $n(7) $n(182) $linkBW 320ms DropTail
	$ns duplex-link $n(7) $n(180) $linkBW 300ms DropTail
	$ns duplex-link $n(8) $n(9) $linkBW 160ms DropTail
	$ns duplex-link $n(8) $n(11) $linkBW 210ms DropTail
	$ns duplex-link $n(9) $n(10) $linkBW 290ms DropTail
	$ns duplex-link $n(9) $n(11) $linkBW 210ms DropTail
	$ns duplex-link $n(10) $n(11) $linkBW 120ms DropTail
	$ns duplex-link $n(12) $n(15) $linkBW 230ms DropTail
	if {$verbose} { puts -nonewline "60..."; flush stdout }
	$ns duplex-link $n(12) $n(16) $linkBW 310ms DropTail
	$ns duplex-link $n(12) $n(19) $linkBW 190ms DropTail
	$ns duplex-link $n(13) $n(14) $linkBW 430ms DropTail
	$ns duplex-link $n(13) $n(16) $linkBW 50ms DropTail
	$ns duplex-link $n(13) $n(18) $linkBW 340ms DropTail
	$ns duplex-link $n(13) $n(19) $linkBW 220ms DropTail
	$ns duplex-link $n(15) $n(16) $linkBW 290ms DropTail
	$ns duplex-link $n(15) $n(17) $linkBW 270ms DropTail
	$ns duplex-link $n(15) $n(18) $linkBW 40ms DropTail
	$ns duplex-link $n(16) $n(19) $linkBW 170ms DropTail
	if {$verbose} { puts -nonewline "70..."; flush stdout }
	$ns duplex-link $n(17) $n(18) $linkBW 300ms DropTail
	$ns duplex-link $n(18) $n(19) $linkBW 310ms DropTail
	$ns duplex-link $n(20) $n(22) $linkBW 150ms DropTail
	$ns duplex-link $n(21) $n(22) $linkBW 350ms DropTail
	$ns duplex-link $n(23) $n(24) $linkBW 230ms DropTail
	$ns duplex-link $n(23) $n(25) $linkBW 160ms DropTail
	$ns duplex-link $n(23) $n(27) $linkBW 250ms DropTail
	$ns duplex-link $n(24) $n(27) $linkBW 270ms DropTail
	$ns duplex-link $n(24) $n(28) $linkBW 90ms DropTail
	$ns duplex-link $n(25) $n(26) $linkBW 260ms DropTail
	if {$verbose} { puts -nonewline "80..."; flush stdout }
	$ns duplex-link $n(26) $n(27) $linkBW 110ms DropTail
	$ns duplex-link $n(29) $n(31) $linkBW 130ms DropTail
	$ns duplex-link $n(29) $n(32) $linkBW 210ms DropTail
	$ns duplex-link $n(29) $n(33) $linkBW 200ms DropTail
	$ns duplex-link $n(29) $n(35) $linkBW 220ms DropTail
	$ns duplex-link $n(29) $n(36) $linkBW 180ms DropTail
	$ns duplex-link $n(29) $n(37) $linkBW 110ms DropTail
	$ns duplex-link $n(30) $n(33) $linkBW 210ms DropTail
	$ns duplex-link $n(30) $n(35) $linkBW 80ms DropTail
	$ns duplex-link $n(31) $n(34) $linkBW 280ms DropTail
	if {$verbose} { puts -nonewline "90..."; flush stdout }
	$ns duplex-link $n(31) $n(36) $linkBW 140ms DropTail
	$ns duplex-link $n(32) $n(33) $linkBW 240ms DropTail
	$ns duplex-link $n(32) $n(36) $linkBW 40ms DropTail
	$ns duplex-link $n(33) $n(34) $linkBW 280ms DropTail
	$ns duplex-link $n(33) $n(35) $linkBW 260ms DropTail
	$ns duplex-link $n(33) $n(36) $linkBW 250ms DropTail
	$ns duplex-link $n(33) $n(37) $linkBW 310ms DropTail
	$ns duplex-link $n(34) $n(36) $linkBW 360ms DropTail
	$ns duplex-link $n(34) $n(37) $linkBW 160ms DropTail
	$ns duplex-link $n(35) $n(36) $linkBW 40ms DropTail
	if {$verbose} { puts -nonewline "100..."; flush stdout }
	$ns duplex-link $n(35) $n(37) $linkBW 290ms DropTail
	$ns duplex-link $n(36) $n(37) $linkBW 250ms DropTail
	$ns duplex-link $n(38) $n(39) $linkBW 80ms DropTail
	$ns duplex-link $n(38) $n(40) $linkBW 180ms DropTail
	$ns duplex-link $n(38) $n(41) $linkBW 140ms DropTail
	$ns duplex-link $n(39) $n(40) $linkBW 170ms DropTail
	$ns duplex-link $n(39) $n(41) $linkBW 180ms DropTail
	$ns duplex-link $n(39) $n(42) $linkBW 70ms DropTail
	$ns duplex-link $n(39) $n(44) $linkBW 200ms DropTail
	$ns duplex-link $n(40) $n(44) $linkBW 260ms DropTail
	if {$verbose} { puts -nonewline "110..."; flush stdout }
	$ns duplex-link $n(41) $n(42) $linkBW 240ms DropTail
	$ns duplex-link $n(41) $n(44) $linkBW 130ms DropTail
	$ns duplex-link $n(42) $n(43) $linkBW 190ms DropTail
	$ns duplex-link $n(42) $n(44) $linkBW 230ms DropTail
	$ns duplex-link $n(43) $n(44) $linkBW 220ms DropTail
	$ns duplex-link $n(45) $n(48) $linkBW 40ms DropTail
	$ns duplex-link $n(46) $n(48) $linkBW 90ms DropTail
	$ns duplex-link $n(46) $n(49) $linkBW 70ms DropTail
	$ns duplex-link $n(46) $n(50) $linkBW 90ms DropTail
	$ns duplex-link $n(47) $n(48) $linkBW 180ms DropTail
	if {$verbose} { puts -nonewline "120..."; flush stdout }
	$ns duplex-link $n(47) $n(49) $linkBW 30ms DropTail
	$ns duplex-link $n(47) $n(50) $linkBW 120ms DropTail
	$ns duplex-link $n(48) $n(50) $linkBW 160ms DropTail
	$ns duplex-link $n(51) $n(52) $linkBW 160ms DropTail
	$ns duplex-link $n(51) $n(54) $linkBW 270ms DropTail
	$ns duplex-link $n(52) $n(54) $linkBW 290ms DropTail
	$ns duplex-link $n(52) $n(55) $linkBW 250ms DropTail
	$ns duplex-link $n(53) $n(55) $linkBW 190ms DropTail
	$ns duplex-link $n(56) $n(59) $linkBW 290ms DropTail
	$ns duplex-link $n(56) $n(60) $linkBW 340ms DropTail
	if {$verbose} { puts -nonewline "130..."; flush stdout }
	$ns duplex-link $n(57) $n(59) $linkBW 410ms DropTail
	$ns duplex-link $n(58) $n(60) $linkBW 260ms DropTail
	$ns duplex-link $n(59) $n(60) $linkBW 80ms DropTail
	$ns duplex-link $n(61) $n(62) $linkBW 260ms DropTail
	$ns duplex-link $n(61) $n(64) $linkBW 290ms DropTail
	$ns duplex-link $n(61) $n(65) $linkBW 120ms DropTail
	$ns duplex-link $n(61) $n(66) $linkBW 250ms DropTail
	$ns duplex-link $n(62) $n(63) $linkBW 390ms DropTail
	$ns duplex-link $n(62) $n(64) $linkBW 70ms DropTail
	$ns duplex-link $n(62) $n(66) $linkBW 240ms DropTail
	if {$verbose} { puts -nonewline "140..."; flush stdout }
	$ns duplex-link $n(63) $n(65) $linkBW 390ms DropTail
	$ns duplex-link $n(63) $n(66) $linkBW 150ms DropTail
	$ns duplex-link $n(64) $n(66) $linkBW 200ms DropTail
	$ns duplex-link $n(67) $n(68) $linkBW 310ms DropTail
	$ns duplex-link $n(67) $n(71) $linkBW 360ms DropTail
	$ns duplex-link $n(68) $n(69) $linkBW 50ms DropTail
	$ns duplex-link $n(69) $n(70) $linkBW 160ms DropTail
	$ns duplex-link $n(69) $n(71) $linkBW 140ms DropTail
	$ns duplex-link $n(72) $n(74) $linkBW 50ms DropTail
	$ns duplex-link $n(73) $n(75) $linkBW 420ms DropTail
	if {$verbose} { puts -nonewline "150..."; flush stdout }
	$ns duplex-link $n(74) $n(75) $linkBW 230ms DropTail
	$ns duplex-link $n(76) $n(77) $linkBW 120ms DropTail
	$ns duplex-link $n(76) $n(78) $linkBW 230ms DropTail
	$ns duplex-link $n(76) $n(80) $linkBW 220ms DropTail
	$ns duplex-link $n(76) $n(82) $linkBW 100ms DropTail
	$ns duplex-link $n(76) $n(83) $linkBW 50ms DropTail
	$ns duplex-link $n(77) $n(78) $linkBW 130ms DropTail
	$ns duplex-link $n(77) $n(79) $linkBW 280ms DropTail
	$ns duplex-link $n(77) $n(82) $linkBW 210ms DropTail
	$ns duplex-link $n(77) $n(83) $linkBW 90ms DropTail
	if {$verbose} { puts -nonewline "160..."; flush stdout }
	$ns duplex-link $n(77) $n(84) $linkBW 80ms DropTail
	$ns duplex-link $n(78) $n(79) $linkBW 330ms DropTail
	$ns duplex-link $n(78) $n(80) $linkBW 80ms DropTail
	$ns duplex-link $n(78) $n(84) $linkBW 140ms DropTail
	$ns duplex-link $n(78) $n(85) $linkBW 180ms DropTail
	$ns duplex-link $n(79) $n(80) $linkBW 270ms DropTail
	$ns duplex-link $n(79) $n(81) $linkBW 220ms DropTail
	$ns duplex-link $n(79) $n(82) $linkBW 190ms DropTail
	$ns duplex-link $n(79) $n(84) $linkBW 210ms DropTail
	$ns duplex-link $n(80) $n(81) $linkBW 260ms DropTail
	if {$verbose} { puts -nonewline "170..."; flush stdout }
	$ns duplex-link $n(80) $n(82) $linkBW 310ms DropTail
	$ns duplex-link $n(80) $n(83) $linkBW 220ms DropTail
	$ns duplex-link $n(80) $n(84) $linkBW 120ms DropTail
	$ns duplex-link $n(82) $n(84) $linkBW 190ms DropTail
	$ns duplex-link $n(83) $n(85) $linkBW 220ms DropTail
	$ns duplex-link $n(86) $n(87) $linkBW 290ms DropTail
	$ns duplex-link $n(86) $n(89) $linkBW 300ms DropTail
	$ns duplex-link $n(86) $n(90) $linkBW 150ms DropTail
	$ns duplex-link $n(86) $n(92) $linkBW 50ms DropTail
	$ns duplex-link $n(87) $n(89) $linkBW 20ms DropTail
	if {$verbose} { puts -nonewline "180..."; flush stdout }
	$ns duplex-link $n(87) $n(90) $linkBW 140ms DropTail
	$ns duplex-link $n(87) $n(92) $linkBW 250ms DropTail
	$ns duplex-link $n(88) $n(89) $linkBW 380ms DropTail
	$ns duplex-link $n(88) $n(90) $linkBW 220ms DropTail
	$ns duplex-link $n(88) $n(91) $linkBW 250ms DropTail
	$ns duplex-link $n(88) $n(92) $linkBW 130ms DropTail
	$ns duplex-link $n(89) $n(90) $linkBW 160ms DropTail
	$ns duplex-link $n(89) $n(92) $linkBW 270ms DropTail
	$ns duplex-link $n(90) $n(92) $linkBW 130ms DropTail
	$ns duplex-link $n(91) $n(92) $linkBW 250ms DropTail
	if {$verbose} { puts -nonewline "190..."; flush stdout }
	$ns duplex-link $n(93) $n(95) $linkBW 90ms DropTail
	$ns duplex-link $n(93) $n(97) $linkBW 240ms DropTail
	$ns duplex-link $n(94) $n(95) $linkBW 200ms DropTail
	$ns duplex-link $n(94) $n(96) $linkBW 100ms DropTail
	$ns duplex-link $n(94) $n(97) $linkBW 20ms DropTail
	$ns duplex-link $n(95) $n(96) $linkBW 300ms DropTail
	$ns duplex-link $n(95) $n(98) $linkBW 200ms DropTail
	$ns duplex-link $n(96) $n(98) $linkBW 150ms DropTail
	$ns duplex-link $n(99) $n(100) $linkBW 90ms DropTail
	$ns duplex-link $n(99) $n(104) $linkBW 290ms DropTail
	if {$verbose} { puts -nonewline "200..."; flush stdout }
	$ns duplex-link $n(99) $n(105) $linkBW 60ms DropTail
	$ns duplex-link $n(99) $n(109) $linkBW 70ms DropTail
	$ns duplex-link $n(100) $n(102) $linkBW 260ms DropTail
	$ns duplex-link $n(100) $n(103) $linkBW 130ms DropTail
	$ns duplex-link $n(100) $n(105) $linkBW 80ms DropTail
	$ns duplex-link $n(100) $n(106) $linkBW 350ms DropTail
	$ns duplex-link $n(101) $n(102) $linkBW 20ms DropTail
	$ns duplex-link $n(101) $n(104) $linkBW 90ms DropTail
	$ns duplex-link $n(101) $n(105) $linkBW 280ms DropTail
	$ns duplex-link $n(101) $n(106) $linkBW 90ms DropTail
	if {$verbose} { puts -nonewline "210..."; flush stdout }
	$ns duplex-link $n(101) $n(107) $linkBW 310ms DropTail
	$ns duplex-link $n(102) $n(103) $linkBW 210ms DropTail
	$ns duplex-link $n(102) $n(104) $linkBW 90ms DropTail
	$ns duplex-link $n(102) $n(105) $linkBW 260ms DropTail
	$ns duplex-link $n(102) $n(106) $linkBW 110ms DropTail
	$ns duplex-link $n(102) $n(108) $linkBW 250ms DropTail
	$ns duplex-link $n(103) $n(105) $linkBW 200ms DropTail
	$ns duplex-link $n(104) $n(106) $linkBW 80ms DropTail
	$ns duplex-link $n(104) $n(108) $linkBW 280ms DropTail
	$ns duplex-link $n(105) $n(107) $linkBW 400ms DropTail
	if {$verbose} { puts -nonewline "220..."; flush stdout }
	$ns duplex-link $n(106) $n(107) $linkBW 300ms DropTail
	$ns duplex-link $n(106) $n(108) $linkBW 210ms DropTail
	$ns duplex-link $n(106) $n(109) $linkBW 300ms DropTail
	$ns duplex-link $n(110) $n(111) $linkBW 50ms DropTail
	$ns duplex-link $n(110) $n(112) $linkBW 290ms DropTail
	$ns duplex-link $n(110) $n(114) $linkBW 500ms DropTail
	$ns duplex-link $n(111) $n(112) $linkBW 240ms DropTail
	$ns duplex-link $n(111) $n(114) $linkBW 470ms DropTail
	$ns duplex-link $n(111) $n(115) $linkBW 310ms DropTail
	$ns duplex-link $n(112) $n(113) $linkBW 150ms DropTail
	if {$verbose} { puts -nonewline "230..."; flush stdout }
	$ns duplex-link $n(113) $n(115) $linkBW 110ms DropTail
	$ns duplex-link $n(116) $n(117) $linkBW 100ms DropTail
	$ns duplex-link $n(116) $n(118) $linkBW 240ms DropTail
	$ns duplex-link $n(116) $n(119) $linkBW 100ms DropTail
	$ns duplex-link $n(117) $n(118) $linkBW 310ms DropTail
	$ns duplex-link $n(117) $n(119) $linkBW 100ms DropTail
	$ns duplex-link $n(120) $n(124) $linkBW 340ms DropTail
	$ns duplex-link $n(121) $n(122) $linkBW 260ms DropTail
	$ns duplex-link $n(121) $n(124) $linkBW 180ms DropTail
	$ns duplex-link $n(123) $n(124) $linkBW 460ms DropTail
	if {$verbose} { puts -nonewline "240..."; flush stdout }
	$ns duplex-link $n(125) $n(127) $linkBW 170ms DropTail
	$ns duplex-link $n(126) $n(127) $linkBW 180ms DropTail
	$ns duplex-link $n(126) $n(128) $linkBW 140ms DropTail
	$ns duplex-link $n(129) $n(131) $linkBW 190ms DropTail
	$ns duplex-link $n(129) $n(132) $linkBW 120ms DropTail
	$ns duplex-link $n(129) $n(133) $linkBW 100ms DropTail
	$ns duplex-link $n(130) $n(131) $linkBW 240ms DropTail
	$ns duplex-link $n(130) $n(133) $linkBW 70ms DropTail
	$ns duplex-link $n(134) $n(135) $linkBW 30ms DropTail
	$ns duplex-link $n(134) $n(136) $linkBW 270ms DropTail
	if {$verbose} { puts -nonewline "250..."; flush stdout }
	$ns duplex-link $n(134) $n(138) $linkBW 120ms DropTail
	$ns duplex-link $n(135) $n(137) $linkBW 330ms DropTail
	$ns duplex-link $n(136) $n(137) $linkBW 200ms DropTail
	$ns duplex-link $n(136) $n(138) $linkBW 200ms DropTail
	$ns duplex-link $n(139) $n(140) $linkBW 170ms DropTail
	$ns duplex-link $n(139) $n(141) $linkBW 170ms DropTail
	$ns duplex-link $n(139) $n(142) $linkBW 90ms DropTail
	$ns duplex-link $n(139) $n(143) $linkBW 260ms DropTail
	$ns duplex-link $n(140) $n(141) $linkBW 150ms DropTail
	$ns duplex-link $n(143) $n(144) $linkBW 290ms DropTail
	if {$verbose} { puts -nonewline "260..."; flush stdout }
	$ns duplex-link $n(143) $n(145) $linkBW 210ms DropTail
	$ns duplex-link $n(146) $n(147) $linkBW 60ms DropTail
	$ns duplex-link $n(146) $n(148) $linkBW 150ms DropTail
	$ns duplex-link $n(146) $n(149) $linkBW 150ms DropTail
	$ns duplex-link $n(146) $n(150) $linkBW 140ms DropTail
	$ns duplex-link $n(146) $n(152) $linkBW 310ms DropTail
	$ns duplex-link $n(147) $n(154) $linkBW 290ms DropTail
	$ns duplex-link $n(148) $n(149) $linkBW 190ms DropTail
	$ns duplex-link $n(148) $n(151) $linkBW 170ms DropTail
	$ns duplex-link $n(148) $n(152) $linkBW 160ms DropTail
	if {$verbose} { puts -nonewline "270..."; flush stdout }
	$ns duplex-link $n(148) $n(154) $linkBW 120ms DropTail
	$ns duplex-link $n(149) $n(152) $linkBW 340ms DropTail
	$ns duplex-link $n(150) $n(151) $linkBW 70ms DropTail
	$ns duplex-link $n(150) $n(152) $linkBW 320ms DropTail
	$ns duplex-link $n(150) $n(154) $linkBW 330ms DropTail
	$ns duplex-link $n(151) $n(154) $linkBW 280ms DropTail
	$ns duplex-link $n(152) $n(154) $linkBW 140ms DropTail
	$ns duplex-link $n(153) $n(154) $linkBW 70ms DropTail
	$ns duplex-link $n(155) $n(158) $linkBW 100ms DropTail
	$ns duplex-link $n(156) $n(157) $linkBW 100ms DropTail
	if {$verbose} { puts -nonewline "280..."; flush stdout }
	$ns duplex-link $n(156) $n(159) $linkBW 190ms DropTail
	$ns duplex-link $n(156) $n(161) $linkBW 240ms DropTail
	$ns duplex-link $n(157) $n(160) $linkBW 110ms DropTail
	$ns duplex-link $n(158) $n(159) $linkBW 500ms DropTail
	$ns duplex-link $n(158) $n(160) $linkBW 280ms DropTail
	$ns duplex-link $n(158) $n(161) $linkBW 220ms DropTail
	$ns duplex-link $n(160) $n(161) $linkBW 220ms DropTail
	$ns duplex-link $n(162) $n(163) $linkBW 150ms DropTail
	$ns duplex-link $n(162) $n(164) $linkBW 150ms DropTail
	$ns duplex-link $n(162) $n(165) $linkBW 300ms DropTail
	if {$verbose} { puts -nonewline "290..."; flush stdout }
	$ns duplex-link $n(166) $n(167) $linkBW 110ms DropTail
	$ns duplex-link $n(166) $n(168) $linkBW 380ms DropTail
	$ns duplex-link $n(169) $n(172) $linkBW 110ms DropTail
	$ns duplex-link $n(169) $n(175) $linkBW 110ms DropTail
	$ns duplex-link $n(170) $n(171) $linkBW 100ms DropTail
	$ns duplex-link $n(170) $n(172) $linkBW 220ms DropTail
	$ns duplex-link $n(170) $n(175) $linkBW 200ms DropTail
	$ns duplex-link $n(171) $n(175) $linkBW 210ms DropTail
	$ns duplex-link $n(173) $n(174) $linkBW 160ms DropTail
	$ns duplex-link $n(173) $n(175) $linkBW 90ms DropTail
	if {$verbose} { puts -nonewline "300..."; flush stdout }
	$ns duplex-link $n(174) $n(175) $linkBW 250ms DropTail
	$ns duplex-link $n(176) $n(177) $linkBW 240ms DropTail
	$ns duplex-link $n(176) $n(178) $linkBW 140ms DropTail
	$ns duplex-link $n(176) $n(179) $linkBW 170ms DropTail
	$ns duplex-link $n(177) $n(179) $linkBW 150ms DropTail
	$ns duplex-link $n(177) $n(180) $linkBW 140ms DropTail
	$ns duplex-link $n(178) $n(180) $linkBW 220ms DropTail
	$ns duplex-link $n(181) $n(182) $linkBW 140ms DropTail
	$ns duplex-link $n(181) $n(183) $linkBW 460ms DropTail
	$ns duplex-link $n(181) $n(184) $linkBW 260ms DropTail
	if {$verbose} { puts -nonewline "310..."; flush stdout }
	$ns duplex-link $n(182) $n(183) $linkBW 370ms DropTail
	$ns duplex-link $n(183) $n(184) $linkBW 320ms DropTail
	$ns duplex-link $n(183) $n(185) $linkBW 490ms DropTail
	$ns duplex-link $n(186) $n(190) $linkBW 250ms DropTail
	$ns duplex-link $n(186) $n(191) $linkBW 210ms DropTail
	$ns duplex-link $n(186) $n(192) $linkBW 280ms DropTail
	$ns duplex-link $n(186) $n(194) $linkBW 250ms DropTail
	$ns duplex-link $n(187) $n(189) $linkBW 170ms DropTail
	$ns duplex-link $n(187) $n(191) $linkBW 340ms DropTail
	$ns duplex-link $n(187) $n(194) $linkBW 310ms DropTail
	if {$verbose} { puts -nonewline "320..."; flush stdout }
	$ns duplex-link $n(188) $n(189) $linkBW 210ms DropTail
	$ns duplex-link $n(188) $n(192) $linkBW 180ms DropTail
	$ns duplex-link $n(188) $n(193) $linkBW 330ms DropTail
	$ns duplex-link $n(189) $n(190) $linkBW 270ms DropTail
	$ns duplex-link $n(190) $n(191) $linkBW 410ms DropTail
	$ns duplex-link $n(190) $n(194) $linkBW 400ms DropTail
	$ns duplex-link $n(191) $n(192) $linkBW 320ms DropTail
	$ns duplex-link $n(191) $n(193) $linkBW 160ms DropTail
	$ns duplex-link $n(192) $n(193) $linkBW 320ms DropTail
	$ns duplex-link $n(192) $n(194) $linkBW 260ms DropTail
	if {$verbose} { puts -nonewline "330..."; flush stdout }
	$ns duplex-link $n(193) $n(194) $linkBW 220ms DropTail
	$ns duplex-link $n(195) $n(196) $linkBW 290ms DropTail
	$ns duplex-link $n(195) $n(198) $linkBW 100ms DropTail
	$ns duplex-link $n(196) $n(198) $linkBW 210ms DropTail
	$ns duplex-link $n(197) $n(198) $linkBW 220ms DropTail
	$ns duplex-link $n(198) $n(199) $linkBW 210ms DropTail

	if {$verbose} { 
		puts -nonewline "336..."
		flush stdout
		puts "starting"
	}
	return 200}
